### PR TITLE
Hotfixes

### PR DESCRIPTION
**Pull request by aspann**
Ive found two issues during compilation and added some version bumps.

- Fix gnome-control-center (meson.build issue)
- Fix gnome-settings-daemon (wrong include)

And did some Version bumps.. (I personally need evolution-ews, before you're asking)
- Bump to tracker-2.0.4
- Bump to evolution-data-server-3.28.4
- Bump to evolution-3.28.4
- Added evolution-ews-3.28.4
 
Maybe you can reuse my changes or some of them.

### CODE REVIEW

**Comment by hhfeuer** [comment]
You chose a unfortunate time to emerge from this tree;) I was just testing and bumping new versions/fixing little things the last days...so evolution/e-d-s have been bumped to 3.28.4 already. Control-center has also been bumped, I didn't run into any issues, I'll look into it. I already thought about adding evolution-ews, I'll cherry-pick it. Also looking into the tracker bump and the gnome-settings-daemon issue. May take some days, though.

**Comment by aspann** [comment]
Take your time and enjoy your weeekend! 
(sorry for the pull-conflict, I'd recognized it right after the pull..)

You did a really great job with this repo, I stay tuned. :)

**Comment by hhfeuer** [comment]
Did some checking:
The meson syntax error has been fixed on gnome's side in gnome-control-center-3.28.2
gsd-device-manager-udev.h in g-settings-daemon is a wayland include, so you have probably USE="wayland" set. Thus, this is a conditional include but I had a typo in my patch, so fixed it there. Please sync and check.

**Comment by aspann** [comment]
Thanks for pointing this out.
I'll update my portage settings.

I think we can close this now.

**Pull request closed without merging**
